### ISSUE TITLE
How to start transcoding?

### ISSUE THREAD

**Issue by hisaac** [bmhayward/Transcode#5]
I'm confused by how to start the transcoding process using these tools. I dropped my mkvs into the "Convert" folder like [the readme suggests](https://github.com/bmhayward/Transcode#usage), but nothing happened. Is there another step in there somewhere?

**Comment by bmhayward** [comment]
Issac,

Thanks for the question.

Have you restarted since installing Transcode? Occasionally, the launch daemon that handles watching the Convert folder does not start after the initial install.

Let me know if this does not correct the issue.

Thanks,
Brent

**Comment by hisaac** [comment]
Hmm… I tried restarting, but the issue persisted. I then tried reinstalling and restarting, but still nothing.

These are the four launch daemons that were installed:

<img width="1333" alt="screen shot 2017-09-07 at 8 50 41 pm" src="https://user-images.githubusercontent.com/923876/30192647-4eb863d2-940e-11e7-87ad-5e7fb5d2f747.png">

Does that all look legit to you?

**Comment by bmhayward** [comment]
Issac,

That all looks correct.

It appears that the current version of Terminal-Notifier is causing Transcode to halt. I am testing an update and plan on pushing It out sometime next week.

In the mean time, if you want to test the change it is simple. Here is what you need to do:

Using TextWrangler (free on the Mac App Store) not TextEdit, open /usr/local/Transcode/Library/_sendNotification.sh
Edit lines 31 and 33, removing from each line:
-activate com.apple.Terminal

The lines should now look like-

Line 31: terminal-notifier -title "${1}" -message "${3}" -subtitle "${2}" -contentImage "${appIcon}"						# no sound
Line 33: terminal-notifier -title "${1}" -message "${3}" -subtitle "${2}" -sound "${4}"	-contentImage "${appIcon}"				# sound

Save and Quit TextWrangler

Drop a file into the Convert folder and let me know if this corrected the issue.

Thanks,
Brent

**Comment by hisaac** [comment]
I made the edits, but no dice. I first thought maybe it had to do with me using zsh for my shell, but I tried re-installing it using bash and applying the changes you outlined above, but the issue persists.

fwiw, there was an error in the terminal during the install (it's in the middle of the snippet below):

```
Installing brew mp4v2

==> Downloading https://homebrew.bintray.com/bottles/mp4v2-2.0.0.sierra.bottle.1.tar.gz

Already downloaded: /Users/hisaac/Library/Caches/Homebrew/mp4v2-2.0.0.sierra.bottle.1.tar.gz

==> Pouring mp4v2-2.0.0.sierra.bottle.1.tar.gz

🍺  /usr/local/Cellar/mp4v2/2.0.0: 33 files, 4.7MB

Installing brew rsync

Warning: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.

==> Downloading https://homebrew.bintray.com/bottles/rsync-3.1.2.sierra.bottle.tar.gz

Already downloaded: /Users/hisaac/Library/Caches/Homebrew/rsync-3.1.2.sierra.bottle.tar.gz

==> Pouring rsync-3.1.2.sierra.bottle.tar.gz

🍺  /usr/local/Cellar/rsync/3.1.2: 9 files, 746.9KB
```

Unless you have other ideas, I can just wait until you push your fix and try that out. If you'd like to put it up on another branch here, or as a test release, I can pull that down and give it a try.

**Comment by bmhayward** [comment]
Issac,

Thanks for the feedback.

I had a minute this morning to install Transcode on a fresh copy of macOS 10.12.6, and then making the corrections I suggested. I got the same rsync brew error during the install, which is fixed in the upcoming release. That is fine as it only effects remote transcoding. Other than that, everything works as expected.

So, could you provide a couple of other pieces of information:

In ~/Library/Preferences open com.videotranscode.preferences.plist. Look for the key:

IngestDirectoryPath

That should match the location of the Convert folder inside of the Transcode folder. If it does not, open the Settings app in /Transcode and reselect the Convert folder. Let me know if what you find

In /usr/local/Transcode/watchFolder.sh, uncomment the fifth line, by removing the # symbol. The line should now look like:

set -xv; exec 1>>/tmp/watchFolderTraceLog 2>&1

save the file.

In /usr/local/Transcode/batch.command, uncomment the fifth line, by removing the # symbol.

The line should now look like:

set -xv; exec 1>>/private/tmp/batchTraceLog 2>&1

Drop a .mkv or .mp4 file in the Convert folder. A watchFolderTraceLog and batchTraceLog files should be created in /tmp. Please copy and paste the contents of those logs back to me.

Thanks,
Brent

**Comment by hisaac** [comment]
So I looked at the plist file, and it was pointed to the wrong place. It was set to look for the "Convert" folder within the root of my hard drive for some reason. I tried to change the location within the Settings app, and got this error:

<img width="532" alt="screen shot 2017-09-09 at 12 31 14 pm" src="https://user-images.githubusercontent.com/923876/30250604-ba5bf50e-9616-11e7-8fce-4067ff3247a6.png">

I was able to change the directory directly inside the plist though, and it then showed up correctly within the Settings app. It still didn't start transcoding when I dropped .mkv files into the folder though, so there's still something going on.

It doesn't look like any log files were generated in the `/tmp` directory, because no transcoding actually happened. Is there a specific file or directory name I should be looking for?

At this point, I'm ok holding off on troubleshooting, and just waiting until you release a next build. I can use the `transcode-video` commands directly from Don Melton until then.

**Comment by bmhayward** [comment]
Issac,

Since no log files were generated, that tells me the LaunchAgent in ~/Library/LaunchAgents/com.videotranscode.watchfolder.plist, is not pointed to the correct Convert folder.

Reselecting the Convert folder or selecting a different folder for ingest using the Settings app will correct the LaunchAgent. This version requires reselecting the ingest folder with the Settings app if you move it from the install location. The upcoming version will follow the ingest folder and make automatic updates if it is moved.

If you decide to wait for the next update, rather than letting Transcode update itself, I would prefer that you uninstall and reinstall. The uninstaller is located in /usr/local/uninstaller.command.

If you have any questions, please let me know.

Thanks,
Brent
